### ISSUE TITLE
Search Input Placeholder Text on FireFox is too small to read

### ISSUE THREAD

**Issue by tmathews** [monstercat/deon#229]
![eyj1cmwioijodhrwczovl2rpc2nvcmquc3rvcmfnzs5nb29nbgvhcglzlmnvbs9hdhrhy2htzw50cy8ymda2nti0odc0ote4ndyxndqvmzaymdg3ntc2ntmymdi1mzq0l01dx1nlyxjjac5wbmcifq](https://cloud.githubusercontent.com/assets/522209/25014162/792bb15c-202b-11e7-94ec-c496eb16aab1.png)

**Comment by ArcticAvenger** [comment]
Hi, I took a look and I think the issue is in /src/css/base.css on line 65, where the padding seems to be affecting the input box.

I was messing around and I think something like "padding: 0.6rem 1rem 0.4rem 1rem" would work in place of "padding: 1rem". I would've made a commit and pull request but frankly I'm new and have no clue how things are done around here so I wasn't sure where I should make the changes and how (I'm also somewhat new to html, css, and js so sorry if I seem a little inexperienced because I am).

PS I'd love to be more involved in the future in any public projects or with any issues so any tips as to how to go about doing that would be great

**Comment by Foxtrek64** [comment]
@ArcticAvenger Slightly off-topic, but here on Github, we tend to treat code edits like Wikipedia. In other words, we have one rule: [be bold](https://en.wikipedia.org/wiki/Wikipedia:Be_bold). If you see something is broken or you see something can be done more efficiently, fork the file(s), make your changes, and make a pull request. Worst case, you gain valuable experience with the coding/scripting language and what the app developer is looking for.

That said, your fix was spot on, so I went ahead and made a pull request using your changes. Trust in your trial and error. As a professional application developer, I can tell you that there is no better teacher. If you find the solution, don't be afraid to apply the fix.

Happy coding!
