### ISSUE TITLE
Longer login sessions?

### ISSUE THREAD

**Issue by SpectralKH** [monstercat/deon#389]
I don't know how often I have to re-login, but it feels like it's every month. At least annoyingly often. Could the sessions last a year instead, like on most websites?

**Comment by tmathews** [comment]
We'll look into it, it could pose security issues and is usually bad practice. You are probably seeing frequent need to re-login due to change in server providers recently.

**Comment by SpectralKH** [comment]
Sure, it's worse to have a longer session in terms of security, but even Google keeps the session for a year. I doubt it's bad practice if Google does it with their 1 billion users. And it hasn't been just recently, I think it's been going on for as long as I can remember.

Shouldn't the session storage be transferred from one server provider to another, along with user data?

**Comment by mistermantas** [comment]
Google has lots of little services and it’s not a ‘dangerous’ action to comment on a video but it is potentially dangerous when making a purchase or changing security settings, which is why you’re prompted to enter your login credentials again.

This same principal could be used on the site, although it’s still more things to be worried about by the devs.

**Comment by Xerus2000** [comment]
btw this is due to the `connect.sid` cookie only being valid for a week, and it is what keeps you logged in

**Comment by tmathews** [comment]
I like the password re-entry idea. Time has been increased significantly beyond 7 days.
